### ISSUE TITLE
NloG自带的和新增到LogModel继承类自定义的项 在其他里面都看不到

### ISSUE THREAD

**Issue by JOJOJOFran** [liangshiw/LogDashboard#16]
![image](https://user-images.githubusercontent.com/19874689/51240158-18a94700-19b6-11e9-8c79-1ea9a37f8a06.png)
![image](https://user-images.githubusercontent.com/19874689/51240227-4098aa80-19b6-11e9-9794-dfb17237424d.png)

NloG自带的和新增到LogModel继承类自定义的项 在其他里面都看不到

**Comment by liangshiw** [comment]
请分享你的startup.cs代码

**Comment by JOJOJOFran** [comment]
![image](https://user-images.githubusercontent.com/19874689/51241490-e220fb80-19b8-11e9-9624-119254c1aaa6.png)

**Comment by liangshiw** [comment]
你可以建一个仓库把代码提交上去，我看看原因

**Comment by JOJOJOFran** [comment]
自定义类 配置不完全导致的 已在PR里说明
