### ISSUE TITLE
建议用异步方式刷新 并且提供缓存方式查阅，这个还是比较有用的

### ISSUE THREAD

**Issue by JOJOJOFran** [liangshiw/LogDashboard#18]

**Comment by liangshiw** [comment]
嗯，我在1.1版本有计划对文件源进行缓存，不过还有些细节需要思考

**Comment by JOJOJOFran** [comment]
嗯 包括Redis，然后可能确实有很多细节需要调整的

**Comment by liangshiw** [comment]
redis倒是优先级比较低，我希望可以抽象出一个缓存接口，默认InMemory实现 。 其他的就可以单独写实现做为一个单独的nuget package发布。比如 `LogDashboard.RedisCache`

**Comment by liangshiw** [comment]
Async Query https://github.com/liangshiw/LogDashboard/commit/e17779692b195ac3f6a48e759a2d8866f2c2e7aa

**Comment by liangshiw** [comment]
@JOJOJOFran  缓存与已经都已经添加
