### ISSUE TITLE
ABP使用此框架添加登录验证

### ISSUE THREAD

**Issue by guaicaiboshi** [liangshiw/LogDashboard#23]
https://mp.weixin.qq.com/s/AeLQd4qybXbqIl-BhcElDg
我参考这个在ABP框架增加了日志框架，但是想添加授权访问，参考
https://logboard.lpflipped.xin/doc/shou-quan-xian-zhi-fang-wen-ri-zhi-mian-ban.html

 services.AddLogDashboard(opt =>
    {
        opt.AddAuthorizeAttribute(new AuthorizeAttribute());
        opt.AddAuthorizationFilter(new SamplesAuthorizationFilter());
    });

但是现在无法访问/logdashboard 了，如果不加这个授权访问是可以的。请指点

**Comment by liangshiw** [comment]
好的，我看一下

**Comment by liangshiw** [comment]
使用 `AbpMvcAuthorizeAttribute`
