### ISSUE TITLE
linux 发布报错如下

### ISSUE THREAD

**Issue by JOJOJOFran** [liangshiw/LogDashboard#31]
Cannot find compilation library location for package 'Microsoft.AspNet.WebApi.Client'

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.105 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by liangshiw** [comment]
OK, 我会检查它，谢谢

**Comment by likeshan168** [comment]
我也碰到这个问题，请问有什么办法吗

**Comment by liangshiw** [comment]
@JOJOJOFran  @likeshan168  请看文档 https://logdashboard.net/doc/index.html#%E5%8F%91%E5%B8%83%E6%97%B6%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F
