### ISSUE TITLE
日志面板异常

### ISSUE THREAD

**Issue by zouql** [liangshiw/LogDashboard#33]
当前使用版本为1.2.2，站点host为：https://localhost:44301，访问https://localhost:44301/LogDashboard/出现异常，但访问https://localhost:44301/LogDashboard/Dashboard是正常的，而且1.1.1版没有该问题。

**Comment by liangshiw** [comment]
可以提供堆栈日志吗

**Comment by zouql** [comment]
大神可能误会了，并没有报错。按照预期结果，请求localhost:44301/LogDashboard应该返回日志主页的，但当前返回了“value”这个字符串，请求https://localhost:44301/LogDashboard/Dashboard能正常的日志页面，windows下和linux下情况一样

**Comment by liangshiw** [comment]
可以提供简单的示例吗？

**Comment by zouql** [comment]
找到原因了，是使用不当，1.2.2版LogDashBoard要求在UseMvc前注入。感谢作者开源此工具，给我们提供了极大的便利。
