### ISSUE TITLE
core3.0下使用异常

### ISSUE THREAD

**Issue by zouql** [liangshiw/LogDashboard#36]
新建一个core3.0web项目，通过nuget包管理器安装了LogDashboard，配置代码如下：
services.AddLogDashboard(config =>
            {
                config.AddAuthorizeAttribute(new AuthorizeAttribute());
            });  报错代码：config.AddAuthorizeAttribute(new AuthorizeAttribute());  报错信息：>Startup.cs(32,17,32,45): error CS7069: 对类型“IAuthorizeData”的引用声称该类型是在“Microsoft.AspNetCore.Authorization”中定义的，但未能找到。 core3.0下，Hangfire未出现异常。

**Comment by liangshiw** [comment]
我还没有适配3.0,请关注 https://github.com/liangshiw/LogDashboard/issues/34
