### ISSUE TITLE
LogDashboardOptions的AddAuthorizeAttribute异常 .NetStandard2.1

### ISSUE THREAD

**Issue by Maple512** [liangshiw/LogDashboard#41]
> 今天刚拉取的最新代码，使用项目：NetCoreEmptyTest.Startup

![Logdashaboard-AuthorizeAttribute-error](https://user-images.githubusercontent.com/34236341/67174599-3009da80-f3f5-11e9-9669-a7fc115e26a2.png)

**Comment by liangshiw** [comment]
https://github.com/liangshiw/LogDashboard/pull/40
I will release a version

**Comment by Maple512** [comment]
Thanks
