### ISSUE TITLE
log4net 文件配置

### ISSUE THREAD

**Issue by newrohlzy** [liangshiw/LogDashboard#43]
首先，感谢楼主分享。有个问题希望可以解惑
刷新页面无法获取最新的日志？在debug模式必须重新运行才可以刷新

环境：.net core 2.2  abp.net 4.3 logDashboard 1.2

**Comment by liangshiw** [comment]
也许是你的日志策略的问题吧，可以提供更多信息？

**Comment by newrohlzy** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<log4net>
  <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender" >
    <file value="App_Data/LogFiles/Logs.log" />
    <appendToFile value="true" />
    <rollingStyle value="Size" />
    <maxSizeRollBackups value="10" />
    <maximumFileSize value="10000KB" />
    <staticLogFileName value="true" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date || %5level || %logger || %message || %exception ||end %newline" />
    </layout>
  </appender>
  <root>
    <appender-ref ref="RollingFileAppender" />
    <level value="All" />
  </root>
</log4net>

这是log4net.config

**Comment by newrohlzy** [comment]
以下为log4net配置：

<?xml version="1.0" encoding="utf-8" ?>
<log4net>
  <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender" >
    <file value="App_Data/LogFiles/Logs.log" />
    <appendToFile value="true" />
    <rollingStyle value="Size" />
    <maxSizeRollBackups value="10" />
    <maximumFileSize value="10000KB" />
    <staticLogFileName value="true" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date || %5level || %logger || %message || %exception ||end %newline" />
    </layout>
  </appender>
  <root>
    <appender-ref ref="RollingFileAppender" />
    <level value="All" />
  </root>
</log4net>

**Comment by newrohlzy** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<log4net>
  <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender" >
    <file value="App_Data/LogFiles/Logs.log" />
    <appendToFile value="true" />
    <rollingStyle value="Size" />
    <maxSizeRollBackups value="10" />
    <maximumFileSize value="10000KB" />
    <staticLogFileName value="true" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date || %5level || %logger || %message || %exception ||end %newline" />
    </layout>
  </appender>
  <root>
    <appender-ref ref="RollingFileAppender" />
    <level value="All" />
  </root>
</log4net>

**Comment by liangshiw** [comment]
这样，你弄一个简单的示例给我吧。我看一下

**Comment by newrohlzy** [comment]
我怎么提交给你？

**Comment by liangshiw** [comment]
上传附件到这里就可以了

**Comment by liangshiw** [comment]
如果你有疑问，可以再打开此issues
