### ISSUE TITLE
使用LogDashboard遇到的一些BUG

### ISSUE THREAD

**Issue by Rhyheart** [liangshiw/LogDashboard#44]
首先，感谢作者的贡献，辛苦了，LogDashboard功能很强大，界面很好看！我刚刚昨天用，版本是1.2.3，因为我现在用的VS2017，暂时也不打算升级的19（兼顾到我们现在的团队），所以无法升级到最新版，不知道以下问题是否在其他版本中已经修复，也非常期待作者能够兼容VS2017，兼容2.0标准库。
![兼容问题](https://user-images.githubusercontent.com/44357526/68451290-266fd780-0229-11ea-9b6b-40294dd4cccb.png)

**Comment by Rhyheart** [comment]
【兼容问题】
如图所示
![兼容问题](https://user-images.githubusercontent.com/44357526/68450831-5cac5780-0227-11ea-8798-3314dabbb475.png)

**Comment by Rhyheart** [comment]
【查询时，ID自增BUG】
![查询时，ID自增BUG](https://user-images.githubusercontent.com/44357526/68450892-9715f480-0227-11ea-99b9-d5ebd2136ec0.gif)

**Comment by Rhyheart** [comment]
【某些情况下点击日志详情报错】
![某些情况下点击日志详情报错](https://user-images.githubusercontent.com/44357526/68450933-b44ac300-0227-11ea-8709-bf9d5af47518.gif)

**Comment by Rhyheart** [comment]
【分页显示异常】
![分页显示异常](https://user-images.githubusercontent.com/44357526/68450955-cd537400-0227-11ea-9b27-2251e1004c51.gif)

**Comment by Rhyheart** [comment]
【这是测试日志】
[2019-11-07.log](https://github.com/liangshiw/LogDashboard/files/3823043/2019-11-07.log)

**Comment by Rhyheart** [comment]
【折线图不完整】
![Uploading 折线图只显示错误日志和所有日志，不支持其他类型.gif…]()

**Comment by liangshiw** [comment]
check

**Comment by liangshiw** [comment]
https://github.com/liangshiw/LogDashboard/issues/46

**Comment by liangshiw** [comment]
https://github.com/liangshiw/LogDashboard/commit/85d760ec3174901338006e30f2eb7d057d26e6cc
