### ISSUE TITLE
和ABPVNEXT集成出错

### ISSUE THREAD

**Issue by haptear** [liangshiw/LogDashboard#45]
# 问题
在abpvnext项目中集成LogDashboard出错
1. 在abp.io网站下载项目模板
![image](https://user-images.githubusercontent.com/16282949/69020124-78191e80-09ee-11ea-897e-eb99fb4e78bd.png)
2. 按照LogDashboard文档引用
3. 执行，直接提示RazorLight相关的异常
![image](https://user-images.githubusercontent.com/16282949/69020322-11e0cb80-09ef-11ea-806e-0a3a517616ee.png)

**Comment by liangshiw** [comment]
做为临时解决方案，添加以下配置到csproj
```
<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
<PreserveCompilationReferences>true</PreserveCompilationReferences>
```
我也在尝试去除razorlight的依赖
https://github.com/liangshiw/LogDashboard/issues/42

**Comment by haptear** [comment]
@liangshiw  按照上面的修过 暂时不起作用。。  等去除了razorlight的版本发布了我再试一试 谢谢楼主提供这么好的项目

**Comment by liangshiw** [comment]
@haptear 我测试一下

**Comment by liangshiw** [comment]
已经解决,下载最新包解决问题 https://www.nuget.org/packages/LogDashboard/1.4.0
示例项目 
[qa.zip](https://github.com/liangshiw/LogDashboard/files/3867440/qa.zip)
