### ISSUE TITLE
支持mongo数据库存储吗

### ISSUE THREAD

**Issue by PomeloButter** [liangshiw/LogDashboard#9]

**Comment by liangshiw** [comment]
Hi. 我封装了仓储，我还没有mongo的仓储实现。如果你需要的话，也可以自行继承
https://github.com/liangshiw/LogDashboard/blob/749f4388680885e43c986ec8f6dae30cd4e75f7f/src/LogDashboard/Repository/IRepository.cs#L9
然后替换仓储。
